spring:
  application:
    name: Eve
  main:
    banner-mode: "off"

server:
  port: 8080

auth:
  client_id: 6f173e1c973d47fdadd63ecc9c2b08ca
  secret_key: jClrWcLY5GjXgU1mIEGh1nG32RjlMN7l2gr01GOe
  path: /v2/oauth/authorize/
  domain: login.eveonline.com
  redirect_uri: http://localhost:4200/auth
  state: nJPh691hf1Paqq6ihR7f4BMB